spring:
  application:
    name: KurseWork
  datasource:
    url: jdbc:postgresql://localhost:5432/MusicWebSiteDB
    username: postgres
    password :
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true